name: zawg
description: "application for marrige"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  animated_splash_screen: ^1.3.0
  splashify: ^0.0.3
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.3+2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  get: ^4.6.6
  line_awesome_flutter: ^3.0.1
  liquid_swipe: ^3.1.0
  cloud_firestore: ^5.0.2
  smooth_page_indicator: ^1.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  form_builder_validators: ^10.0.1
  number_text_input_formatter: ^1.0.0+8
  vertical_weight_slider: ^2.6.0
  syncfusion_flutter_sliders: ^26.1.40
  flutter_material_color_picker: ^1.2.0
  country_picker: ^2.0.26
  getwidget: ^4.0.0
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#f7f6f1"
  image: assets/images/zawj-logo.png
  color_dark: "#272727"
  branding: assets/images/zawj-branding.png
  android_gravity: center
  image_dark: assets/images/zawj-logo.png
  branding_dark: assets/images/zawj-branding.png

  android_12:
    icon_background_color: "#f7f6f1"
    android_gravity: clip_horizontal
    image_dark: assets/images/zawj-logo.png
    icon_background_color_dark: "#272727"
    image: assets/images/zawj-logo.png
    branding: assets/images/zawj-branding.png

  web: false


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
   - assets/images/dashboard/
   - assets/images/forget_password/
   - assets/images/on_boarding_images/
   - assets/images/profile/
   - assets/images/splash_images/
   - assets/images/welcome_images/
   - assets/logo/



