// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKckgPCvqsw1ZXruFElvveTHJssTN04VA',
    appId: '1:272093011852:web:7b9602137c9f5524fa40a9',
    messagingSenderId: '272093011852',
    projectId: 'zawg-5d1f7',
    authDomain: 'zawg-5d1f7.firebaseapp.com',
    storageBucket: 'zawg-5d1f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrXr65sfKcXleNAeyixTnSbrLzHceFPiY',
    appId: '1:272093011852:android:9eb8a3b1c182a849fa40a9',
    messagingSenderId: '272093011852',
    projectId: 'zawg-5d1f7',
    storageBucket: 'zawg-5d1f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOWdNbT2cVr7uxiAnU-dNPmQu5DiVDtRQ',
    appId: '1:272093011852:ios:ce2dd132e36929e1fa40a9',
    messagingSenderId: '272093011852',
    projectId: 'zawg-5d1f7',
    storageBucket: 'zawg-5d1f7.appspot.com',
    iosBundleId: 'com.example.zawg',
  );
}
